# Generated by Django 2.0.6 on 2020-04-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
