# Generated by Django 2.0.6 on 2020-04-22 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_demomodel_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demomodel',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='demomodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
