# Generated by Django 3.0.5 on 2020-05-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
