# Generated by Django 3.0.5 on 2020-05-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200511_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/%Y%m%d'),
        ),
    ]
