# Generated by Django 3.0.5 on 2020-05-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200511_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
