# Generated by Django 2.0.6 on 2020-04-22 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200422_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(default='uuid demo content')),
            ],
        ),
    ]
