# Generated by Django 2.0.6 on 2020-04-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_uuidmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
