# Generated by Django 3.0.5 on 2020-05-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_postqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
