# Generated by Django 2.0.6 on 2020-04-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20200423_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='username',
        ),
    ]
