# Generated by Django 2.0.6 on 2020-04-23 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20200423_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='demo.Group'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
