# Generated by Django 2.0.6 on 2020-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flying_height', models.IntegerField(default=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
