# Generated by Django 2.0.6 on 2020-04-23 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_baby_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='human_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.Human'),
        ),
    ]
