# Generated by Django 2.0.6 on 2020-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_auto_20200423_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Benz',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('demo.person',),
        ),
    ]
