# Generated by Django 2.0.6 on 2020-04-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_benz_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benz',
        ),
        migrations.CreateModel(
            name='MyCar',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('demo.car',),
        ),
    ]
