# Generated by Django 2.0.6 on 2020-04-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_auto_20200423_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycar',
            options={'ordering': ['name']},
        ),
    ]
