# Generated by Django 3.0.5 on 2020-05-20 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.CharField(default='black', max_length=20)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('length', models.IntegerField(default=10)),
            ],
        ),
    ]
