# Generated by Django 3.0.5 on 2020-05-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pen',
            name='purchase_date',
        ),
    ]
