# Generated by Django 3.0.5 on 2020-05-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('mig', '0002_auto_20200519_1659'),
        ('mig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pen',
            name='color',
        ),
        migrations.AddField(
            model_name='pen',
            name='length',
            field=models.IntegerField(default=10),
        ),
    ]
