# Generated by Django 3.0.5 on 2020-05-22 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mig', '0002_remove_pen_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
