# Generated by Django 3.0.5 on 2020-05-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mig', '0003_auto_20200520_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pen',
            name='length',
        ),
        migrations.AddField(
            model_name='pen',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name='pen',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
